### ISSUE TITLE
forestdb batch leakage?

### ISSUE THREAD

**Issue by steveyen** [blevesearch/blevex#4]
In a recent PR, I saw that rocksdb batch was leaking...

https://github.com/blevesearch/blevex/pull/3

Looks like a similar batch leakage issue will exist for forestdb batch...

https://github.com/blevesearch/blevex/blob/master/forestdb/writer.go#L56

**Comment by mschoch** [comment]
Fixed in https://github.com/blevesearch/blevex/commit/79ec1145828bf5979f1a0ad173b60aeeb18756ec
